name: chat_withmoxi
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #for using getx state_management..
  get: ^4.6.6
  velocity_x: ^4.2.1
  #for location we use..
  # geolocator: ^9.0.1
  #for authorization..
  firebase_auth: ^5.3.1
  #for firebase..
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  #for storing media to firebase..
  firebase_storage: ^12.3.4
  #for handling permissions..
  permission_handler: ^11.3.1
  #for image picking.
  image_picker: ^1.1.2
  #image_picker: ^0.8.5+3
  path_provider: ^2.1.4
  #for saving user data in local storage
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: mont
      fonts:
        - asset: assets/fonts/mont.ttf

    - family: lato_bold
      fonts:
        - asset: assets/fonts/mont_bold.ttf
    - family: lato_light
      fonts:
        - asset: assets/fonts/mont_light.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



